name: Tabletop Whale
description: Science infographics and animations
url: http://tabletopwhale.com
author: Eleanor Lutz
email: TabletopWhale@gmail.com

timezone: America/Los_Angeles	
paginate: 3 					
paginate_path: "/page:num"
markdown: kramdown